# Copyright (c) 2019 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
version: '2.4'

services:
  
  #--------------------------------------------------------------------
  # EieManager config container
  #--------------------------------------------------------------------
  eie_manager_config:
    image: docker.io/ericksancho/eie_manager_config:0.0.1
    volumes:
      - ./configs:/configs
      - ./execute:/eieman
    command: python3 /eieman/main.py --config /configs

 